                                                          Basic If-Else Statements:


      1. Write a Python program to check if a given number is positive or negative.


In [4]:
n = float(input('Input a number: '))
print('Number is Positive. '
    if n > 0
else
    'It is Zero!'
    if n == 0
else
    'number is nagitive')
    


Input a number:  .358


Number is Positive. 


      2. Create a program that determines if a person is eligible to vote based on their age.


In [14]:
age = int(input("Enter age : "))
if age >= 18:
    print("Eligible for Voting! ")
else:
    print("Not Eligible for Voting! ")

Enter age :  25


Eligible for Voting! 


       3. Develop a program to find the maximum of two numbers using if-else statements.


In [16]:
num1 = int(input("num1:"))
num2 = int(input("num2:"))

# printing the maximum value
if(num1 > num2):
    print (num1, "is greater")
elif(num1 < num2):
    print(num2, "is greater")
else: 
    print("both are equal")

num1: 10
num2: 50


50 is greater


     4. Write a Python script to classify a given year as a leap year or not.


In [31]:
# Python program to check if year is a leap year or not

year = int(input("enter a year:"))

# To get year (integer input) from the user
# year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))
# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))

enter a year: 2015


2015 is not a leap year


      5. Create a program that checks whether a character is a vowel or a consonant.


In [54]:
# Function to check whether the given character is a vowel or not
character = input("enter a character:")
# Creating a string of vowels.
vowels = "aeiouAEIOU"
# Check if the character is a vowel or not.
if character in vowels:
     print(f"The character '{character}' is a vowel!")
else:
     print(f"The character '{character}' is a consonant!") 

enter a character: a


The character 'a' is a vowel!


       6. Implement a program to determine whether a given number is even or odd

In [13]:
num = int(input("Enter any number to test whether it is odd or even:"))
if (num % 2) == 0:
    print ("The number is even")
else:
    print ("The provided number is odd")

Enter any number to test whether it is odd or even: 65


The provided number is odd


      7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.


In [21]:
num = float(input("Enter any number: "))
if num < 0 :
    print("Here's the absolute value: ", num*-1)
elif num == 0 :
    print("Here's the absolute value: 0")
elif num > 0 :
    print("Here's the absolute value: ", num)

Enter any number:  10


Here's the absolute value:  10.0


     8. Develop a program that determines the largest of three given numbers using if-else statements.


In [1]:
# Python program to find the largest number among the three input numbers

# change the values of num1, num2 and num3
# for a different result
num1 = int(input("enter first number"))
num2 = int(input("enter second number"))
num3 = int(input("enter three number"))

if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print("The largest number is", largest)

enter first number 45
enter second number 14
enter three number 78


The largest number is 78


      9. Create a program that checks if a given string is a palindrome.


In [53]:

def check_palin (str):
    for i in range (0, int (len (str)/2)):
                    if str [i] != str [len (str) -i-1]:
                                   return False 
                    return True
str_1 = input ("Enter a string.")
ans = check_palin (str_1)
if (ans):
    print ("Yes, it is a palindrome.")
else:
    print ("No, it is not a palindrome.")

Enter a string. noton


Yes, it is a palindrome.


      10. Write a Python program to calculate the grade based on a student's score.
      

In [56]:
print("Enter Marks Obtained in 5 Subjects: ")
marks1 = int(input("enter subject 1:"))
marks2 = int(input("enter subject 2:"))
marks3 = int(input("enter subject 3:"))
marks4 = int(input("enter subject 4:"))
marks5 = int(input("enter subject 5:"))

total = marks1+marks2+marks3+marks4+marks5
avg = total/5
if avg>=91 and avg<=100:
    print("Your Grade is A1")
elif avg>=81 and avg<91:
    print("Your Grade is A2")
elif avg>=71 and avg<81:
    print("Your Grade is B1")
elif avg>=61 and avg<71:
    print("Your Grade is B2")
elif avg>=51 and avg<61:
    print("Your Grade is C1")
elif avg>=41 and avg<51:
    print("Your Grade is C2")
elif avg>=31 and avg<=41:
    print("Your Grade is D1")
elif avg>=21 and avg<=31:
    print("Your Grade is D2")
elif avg>=11 and avg<=21:
    print("Your Grade is E1")
elif avg>=0 and avg<=11:
    print("Your Grade is E2")
else:
    print("invalid input")
    



Enter Marks Obtained in 5 Subjects: 


enter subject 1: 58
enter subject 2: 45
enter subject 3: 78
enter subject 4: 96
enter subject 5: 52


Your Grade is B2


                                 Nested If-Else Statements:


      11. Write a program to find the largest among three numbers using nested if-else statements.


In [62]:
x = int(input("Enter first number:"))
y = int(input("Enter second number:"))
z = int(input("Enter third number:"))

if x > y:
    if x > z:
        print("Greatest is x to z:", x)
    else:
        print("Greatest is x to zz:", z)
else:
    if y > z:
        print("Greatest is y to z:", y)
    else:
        print("Greatest isy y to zz:", z)

Enter first number: 45
Enter second number: 12
Enter third number: 23


Greatest is x to z: 45


       12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.


In [65]:
print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

Input lengths of the triangle sides: 


x:  45
y:  45
z:  78


isosceles triangle


      13. Develop a program that checks if a year is a leap year and also if it is a century year.


In [67]:
year=int(input("Enter year to be checked:"))
if(year%4==0 and year%100!=0 or year%400==0):
    print("The year is a leap year!")
else:
    print("The year isn't a leap year!")

Enter year to be checked: 2012


The year is a leap year!


      14. Write a Python script to determine if a number is positive, negative, or zero.


In [74]:
n = float(input("Input a number: "))
if n >= 0:
    if n == 0:
        
        print("It is Zero! ")
    else:
        print("Number is Positive number. ")
else:
    print("Number is Negative number.")

Input a number:  0


It is Zero! 


        15. Create a program to check if a person is a teenager (between 13 and 19 years old).


In [94]:
age = int(input("Enter your age"))
if age <= 13:
    print("Hey! kid")
elif age >= 13 and age <= 20:
    print("So, you are enjoying your teenage.")
else:
    print("You are grown up.")

Enter your age 21


You are grown up.


     16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).


In [12]:
# Python3 program to count of acute, obtuse and right 
# triangles in an array 

# Find the number of acute, right, obtuse triangle 
# that can be formed from given array. 
def findTriangle(a, n) : 
	
	b = [] 
	# Finding the square of each element of array 
	for i in range(n) : 
		b.append(a[i] * a[i]) 
	
	# Sort the sides of array and their squares. 
	a.sort() 
	b.sort() 
	
	# x for acute triangles 
	# y for right triangles 
	# z for obtuse triangles 
	x, y, z = 0, 0, 0
	
	for i in range(n) : 
		p = i+1
		q = i+1
		for j in range(i + 1, n) : 
			# Finding the farthest point p where 
			# a^2 + b^2 >= c^2. 
			while (p<n-1 and b[i]+b[j]>=b[p+1]) : 
				p += 1
			q = max(q, p) 
			# Finding the farthest point q where 
			# a + b > c. 
			while (q<n-1 and a[i]+a[j]>a[q+1]) : 
				q += 1
				
			# If point p make right triangle. 
			if (b[i]+b[j]==b[p]) : 
				# All triangle between j and p are acute 
				# triangles. So add p - j - 1 in x. 
				x += max(p - j - 1, 0) 
				# Increment y by 1. 
				y += 1
				# All triangle between q and p are acute 
				# triangles. So add q - p in z. 
				z += q - p 
			# If no right triangle 
			else : 
				# All triangle between j and p are acute 
				# triangles. So add p - j in x. 
				x += max(p - j, 0) 
				# All triangle between q and p are acute 
				# triangles. So add q - p in z. 
				z += q - p 
	
	print("Acute Triangle:",x ) 
	print("Right Triangle:", y) 
	print("Obtuse Triangle:", z) 


# Driver Code 
if __name__ == "__main__" : 

	arr = [2, 3, 9, 10, 12, 15] 
	n = len(arr) 
	findTriangle(arr, n) 

Acute Triangle: 2
Right Triangle: 1
Obtuse Triangle: 4


      17. Write a Python program to calculate the roots of a quadratic equation.


In [99]:
#Solve the quadratic equation ax**2 + bx + c = 0

# import complex math module
import cmath

a = int(input("enter a value:"))
b = int(input("enter a value:"))
c = int(input("enter a value:"))

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

enter a value: 8
enter a value: 4
enter a value: 5


The solution are (-0.25-0.75j) and (-0.25+0.75j)


    18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2 for Tuesday, etc.).



In [5]:
day = int(input("Enter a number from 1 to 7: "))
if day == 1:
    print(day, "is Sunday")
elif day == 2:
      print(day, "is Monday")
elif day == 3:
      print(day, "is Tuesday")
elif day == 4:
      print(day, "is Wednesday")
elif day == 5:
      print(day, "is Thursday")
elif day == 6:
      print(day, "is Friday")
elif day == 7:
      print(day, "is saturday")
else:
    print(day, "is invalid ")

Enter a number from 1 to 7:  6


6 is Friday


     19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.


In [32]:
# Default function to implement conditions to check leap year.
def CheckLeap(Year):
# Checking if the given year is leap year.
  if((Year % 400 == 0)or 
   (Year % 100 != 0) and
   (Year % 4 == 0)):
    print("Given Year is a leap Year");
# Else it is not a leap year.
  else:  
    print ("Given Year is not a leap Year")  
# Taking an input year from user  
Year = int(input("Enter the number: "))  
# Printing result  
CheckLeap(Year)

Enter the number:  2012


Given Year is a leap Year


      20. Develop a program that checks if a given number is prime or not using nested if-else statements.



In [65]:
from math import sqrt
n = int(input("enter a prime number:" ))
flag = 0
if(n > 1):
    for k in range(2,int(sqrt(n)) + 1):
        if (n % k == 0):
            flag = 1
        break
    if (flag == 0):
        print(n," is a prime number! ")
    else:
        print(n, " is not a prime number! ")
else:
    print(n, " is not a prime number! " )

enter a prime number: 13


13  is a prime number! 


                                                   Elif Statements:



     21. Write a Python program to assign grades based on different ranges of scores using elif statements.


In [83]:
marks = int(input("Enter your mark "))
if(marks>=80):
    print("You got A grade")
elif(marks>=60):
    print("You got B grade")
elif(marks>=40):
    print("You got C grade")
else:
    print("Failed in this Exam ")

Enter your mark  80


You got A grade


    22. Implement a program to determine the type of a triangle based on its angles.


In [110]:
A = int(input("enter the number of 1 : "))
B = int(input("enter the number of 2 : "))
C = int(input("enter the number of 3 : "))

if A+B+C != 180 or A<0 or A>180 or B<0 or B>180 or C<0 or C>180:
    print("NOT TRIANGLE")
elif A<90 and B<90 and C<90:
    print("acute angle")
elif (A>90 and A<180) or (B<90 and B<180) or (C<90 and C<180):
    print("obtus angle")
        
elif A==90 or B==90 or C==90:
    print("carpenter's triangle")
else:
    print("wut?")

enter the number of 1 :  60
enter the number of 2 :  60
enter the number of 3 :  60


acute angle


    23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using elif statement.


In [12]:
#Here is the way
#your code goes here
weight=float(input())
height=float(input())

bmi= weight/(height)**2

if bmi<18.5:
    print("Underweight")
elif bmi>=18.5 and bmi<25:
    print("Normal")
elif bmi>=25 and bmi<30:
    print("Overweight")
else:
    print("Obesity")

 2000
 10


Normal


     24. Create a program that determines whether a given number is positive, negative, or zero using elif statements.



In [3]:
# Default function to run if else condition  
def NumberCheck(x):   
    # Checking if the number is positive  
    if x > 0:   
        print("Number given by you is Positive")   
    # Checking if the number is negative   
    elif x < 0:   
        print("Number given by you is Negative")   
    # Else the number is zero  
    else:   
        print("Number given by you is zero")  
# Taking number from user  
x = float(input("Enter a number as input value: "))  
# Printing result  
NumberCheck(x)  

Enter a number as input value:  25


Number given by you is Positive


     25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif statements.



In [54]:
character = input("Enter a character: ")
import re
if re. match(r'[a-z]+',character):
    print(character, "is a lower case letter.")
elif re. match(r'[A-Z]',character):
    print(character, "is an upper case letter.")
elif re. match(r'[~!@#$%^&*(){}:;?><,.//*=+-_]',character):
    print(character, "is a special case letter.")
else:
    print(character, "is a non alphanumeric letter,")

Enter a character:  {:lkjhbgvcx


{:lkjhbgvcx is a special case letter.


     26. Implement a program to calculate the discounted price based on different purchase amounts using elif statements.



In [16]:
p=int(input('Enter purchase amount '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  50000


Discount Amount = 8000.00
Net Bill Amount = 42000.00


       27. Develop a program to calculate the electricity bill based on different consumption slabs using elif statements.

In [30]:
units=int(input("please enter the number of units you consumed in a month"))
if(units<=100):
    payAmount=units*1.5
    fixedcharge=25.00
elif(units<=200):
    payAmount=(100*1.5)+(units-100)*2.5
    fixedcharge=50.00
elif(units<=300):
    payAmount=(100*1.5)+(200-100)*2.5+(units-200)*4
    fixedcharge=75.00
elif(units<=350):
    payAmount=(100*1.5)+(200-100)*2.5+(300-200)*4+(units-300)*5
    fixedcharge=100.00
else:
    payAmount=0
    fixedcharge=1500.00
Total=payAmount+fixedcharge;
print("\nElecticity bill=%.2f" %Total)

please enter the number of units you consumed in a month 250



Electicity bill=675.00


       28. Create a program to determine the type of quadrilateral based on its angles and sides using elif statements.

In [27]:
# Python implementation 
# of the approach
d =20
a = 0.0
 
# according to formula 
# derived above
a=(360 - (6 * d)) / 4
 
# print all the angles
print(a,",", a + d, ",", a + 2 * d,
        ",", a + 3 * d, sep = ' ')

60.0 , 80.0 , 100.0 , 120.0


    29. Write a Python script to determine the season based on a user-provided month using elif statements.

In [76]:
month = int(input("Enter a month: "))
day = int(input("Enter a day: "))

season = ""

if month == 1 or month == 2 or month == 3:
    season = "Winter"

elif month == 4 or month == 5 or month == 6:
    season = "Spring"

elif month == 7 or month == 8 or month == 9:
    season = "Summer"

elif month == 10 or month == 11 or month == 12:
    season = "Fall"

if month % 3 == 0 and day >= 21:
    if season == "Winter":
        season = "Spring"
    elif season == "Spring":
        season = "Summer"
    elif season == "Summer":
        season = "Fall"
    else:
        season = "Winter"

print("Season is ", season)

Enter a month:  3
Enter a day:  12


Season is  Winter


    30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using elif statements.



In [83]:
month = int(input("enter the month:"))
year=int(input("enter the year:"))
    
if((month==2) and ((year%4==0)  or ((year%100==0) and (year%400==0)))) :
    print("Number of days is 29")

elif(month==2) :
    print("Number of days is 28")

elif(month==1 or month==3 or month==5 or month==7 or month==8 or month==10 or month==12) :
    print("Number of days is 31")

else :
    print("Number of days is 30")

enter the month: 2
enter the year: 2024


Number of days is 29


                                                        Basic Level:


     1. Write a Python program that checks if a given number is positive, negative, or zero.


In [15]:
n = float(input("Input a number:"))


if n > 0:
    print("Number is Positive.")
elif n == 0:
        print("It is Zero!")
else: 
    print("Number is Negative.")

Input a number: 2.0


Number is Positive.


    2. Create a program to determine if a person is eligible to vote based on their age.


In [17]:
age = int(input("Enter age : "))
if age >= 18:
    print("Eligible for Voting! ")
else:
    print("Not Eligible for Voting! ")

Enter age :  20


Eligible for Voting! 


      3. Write a program to find the maximum of two given numbers using conditional statements

In [22]:
# Python program to return maximum of two numbers

# Getting input from user
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# printing the maximum value
if(num1 > num2):
    print(num1, "is greater than num1:")
elif(num1 < num2):
    print(num2, "is greater than num2:")
else:
    print("Both are equal")

Enter the first number:  65
Enter the second number:  25


65 is greater than num1:


     4. Develop a program that calculates the grade of a student based on their exam score.


In [9]:
sub1=int(input("Enter marks of the first subject: "))
sub2=int(input("Enter marks of the second subject: "))
sub3=int(input("Enter marks of the third subject: "))
sub4=int(input("Enter marks of the fourth subject: "))
sub5=int(input("Enter marks of the fifth subject: "))
avg=(sub1+sub2+sub3+sub4+sub4)/5
if(avg>=90):
    print("Grade: A")
elif(avg>=80 and avg<90):
    print("Grade: B")
elif(avg>=70 and avg<80):
    print("Grade: C")
elif(avg>=60 and avg<70):
    print("Grade: D")
else:
    print("Grade: F")

Enter marks of the first subject:  75
Enter marks of the second subject:  45
Enter marks of the third subject:  85
Enter marks of the fourth subject:  57
Enter marks of the fifth subject:  95


Grade: D


     5. Create a program that checks if a year is a leap year or not.


In [10]:
year=int(input("Enter year to be checked:"))
if(year%4==0 and year%100!= 0 or year%400==0):
    print("The year is a leap year!")
else:
    print("The year isn't a leap year!")

Enter year to be checked: 2022


The year isn't a leap year!


      6. Write a program to classify a triangle based on its sides' lengths.


In [19]:
print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

Input lengths of the triangle sides: 


x:  5
y:  5
z:  5


Equilateral triangle


     7. Build a program that determines the largest of three given numbers.


In [5]:
# Python program to find the largest number among the three input numbers

# uncomment following lines to take three numbers from user
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print("The largest number is", largest)

Enter first number:  10
Enter second number:  1.58
Enter third number:  25.56


The largest number is 25.56


             8. Develop a program that checks whether a character is a vowel or a consonant.


In [ ]:
# Python program to check whether the given character  
# is a vowel or consonant  
  
# Get an input character from the user  
character = input("Enter a character: ")  
  
# Creating a list of vowels  
vowels = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']  
  
# Check if the character is a vowel or not  
if character in vowels:  
    print(f"The character is a vowel!")  
else:  
    print(f"The character is a consonant!")  

Enter a character:  bhavesh


The character is a consonant!


                 9. Create a program to calculate the total cost of a shopping cart based on discounts.


In [39]:
drinks = input("How many drinks do you want?")
drinks = int(drinks)

total = 0

single = 1000
six = 100

sixPacks = drinks // 6
singles = drinks % 6
# single * 6 = six

total += six * sixPacks
total += single * singles

if total > 20:
    total *= 0.75

print( "That will be a total of: {} rupees".format(round(total, 2)))

How many drinks do you want? 500


That will be a total of: 7725.0 rupees


   10. Write a program that checks if a given number is even or odd.


In [44]:
num = int (input ("Enter any number to test whether it is odd or even: "))
if (num % 2) == 0:
    print ("The number is even")
else:
    print ("The provided number is odd")

Enter any number to test whether it is odd or even:  55


The provided number is odd


                   Intermediate Level:


      11. Write a program that calculates the roots of a quadratic equation .


In [45]:
# import complex math module  
import cmath  
a = float(input('Enter a: '))  
b = float(input('Enter b: '))  
c = float(input('Enter c: '))  
  
# calculate the discriminant  
d = (b**2) - (4*a*c)  
  
# find two solutions  
sol1 = (-b-cmath.sqrt(d))/(2*a)  
sol2 = (-b+cmath.sqrt(d))/(2*a)  
print('The solution are {0} and {1}'.format(sol1,sol2))

Enter a:  10
Enter b:  10
Enter c:  12


The solution are (-0.5-0.9746794344808963j) and (-0.5+0.9746794344808963j)


     12. Create a program that determines the day of the week based on the day number (1-7).


In [47]:
day = int(input("Enter a number from 1 to 7: "))
if day == 1:
    print(day, "is Sunday")
elif day == 2:
    print(day, "is Monday")
elif day == 3:
    print(day, "is Tuesday")
elif day == 4:
    print(day, "is Wednesday")
elif day == 5:
    print(day, "is Thursday")
elif day == 6:
    print(day, "is Friday")
elif day == 7:
    print(day, "is saturday")

Enter a number from 1 to 7:  5


5 is Thursday


      13. Develop a program that calculates the factorial of a given number using recursion.


In [61]:
# Factorial of a number using recursion

def recur_factorial(n):
    if n == 1:
        return n
    else:
        return n*recur_factorial(n-1)

num = int(input("enter the factorial number:"))

# check if the number is negative
if num < 0:
    print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
    print("The factorial of 0 is 1")
else:
    print("The factorial of", num, "is", recur_factorial(num))

enter the factorial number: 5


The factorial of 5 is 120


      14. Write a program to find the largest among three numbers without using the `max()` function

In [65]:
def maximum(a, b, c): 
 
    if (a >= b) and (a >= c): 
        largest = a 
 
    elif (b >= a) and (b >= c): 
        largest = b 
    else: 
        largest = c 
         
    return largest 
 
 #Driven code 
a = int(input("enter a number1:"))
b = int(input("enter a number2:"))
c = int(input("enter a number3:"))
print("the largest number:",maximum(a, b, c)) 

enter a number1: 10
enter a number2: 14
enter a number3: 48


the largest number: 48


     15. Create a program that simulates a basic ATM transaction menu.


In [67]:
print("welcome to bank of india")
trials = 3
userpin = 1234

while trials != 0:
    pin = int(input("please enter your 4 digit pin number:"))
    if pin != userpin:
        trials -= 1
        print("wrong pin number, you have",trials,"trials left" )
    else:
        userchoice = input("d: deposit or w: withdraw:")
        if userchoice == "d":
            userdeposit = input("enter the amount you would like to deposit:")
            print(userdeposit, "$ have been deposited into your account")
        if userchoice == "w":
            userwithdraw = input("enter the amount you would like to withdraw:")
            print(userwithdraw, "$ have been withdrawn into your account")
        userexit = input("would you like to continue? Y/N:")    
        if userexit == "N":
            print("thank you for using bank of india")
            break
        else:
            continue

welcome to bank of india


please enter your 4 digit pin number: 1234
d: deposit or w: withdraw: d
enter the amount you would like to deposit: 5000


5000 $ have been deposited into your account


would you like to continue? Y/N: N


thank you for using bank of india


     16. Build a program that checks if a given string is a palindrome or not.


In [6]:
str = input()
strstr = str.casefold()
# This string is reverse.
rev = reversed(str)
if list(str) == list(rev):
    print("PALINDROME !")
else:
    print("NOT PALINDROME !")

 javaj


PALINDROME !


     17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values

In [6]:
# Python program to get average of a list 
def Average(lst): 
    return sum(lst) / len(lst) 
 
# Driver Code 
lst = [15, 9, 55, 41, 35, 20, 62, 49 ]
average = Average(lst) 
 
# Printing average of the list 
print("Average of the list =", round(average, 2)) 

Average of the list = 35.75


     18. Develop a program that converts a given temperature from Celsius to Fahrenheit.


In [2]:
celsius = int(input("Enter the Temperature in Celsius :\n"))
fahrenheit = (1.8 * celsius) + 32
print("Temperature in Fahrenheit :", fahrenheit)

Enter the Temperature in Celsius :
 56


Temperature in Fahrenheit : 132.8


    19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.


In [16]:
#Promting input from the user. 
n1 = float(input("Enter the First Number: "))
n2 = float(input("enter the second number:"))
#addition.
print("{} + {} = ". format(n1, n2))
print(n1+n2)
#subtraction. 
print("{} - {} = ". format(n1, n2))
print(n1-n2)
#multiplication. 
print("{} * {} = ". format(n1, n2))
print(n1*n2)
#division. 
print("{} / {} = ". format(n1, n2))
print(n1/n2)

Enter the First Number:  54
enter the second number: 78


54.0 + 78.0 = 
132.0
54.0 - 78.0 = 
-24.0
54.0 * 78.0 = 
4212.0
54.0 / 78.0 = 
0.6923076923076923


     20. Write a program that determines the roots of a cubic equation using the Cardano formula.


In [24]:
import math
 
def cubic_root(n):
    return round(math.exp(math.log(n)/3), 6)
 
n = int(input())
print("Cubic Root of", n, "is", cubic_root(n))
n = int(input())
print("Cubic Root of", n, "is", cubic_root(n))

 8


Cubic Root of 8 is 2.0


 10


Cubic Root of 10 is 2.154435



                           Advanced Level:


     21. Create a program that calculates the income tax based on the user's income and tax brackets.


In [8]:
def calculate(amount, percent): 
	return (amount * percent) / 100

def calculate_income_tax(total_income: float) -> float: 

	if total_income <= 250000: 
		return 0
	elif total_income <= 500000: 
		return calculate(total_income -
						250000, 5) 
	elif total_income <= 750000: 
		return calculate(total_income -
						500000, 10) + 12500
	elif total_income <= 1000000: 
		return calculate(total_income -
						750000, 15) + 37500
	elif total_income <= 1250000: 
		return calculate(total_income -
						1000000, 20) + 75000
	elif total_income <= 1500000: 
		return calculate(total_income -
						1250000, 25) + 125000
	else: 
		return calculate(total_income -
						1500000, 30) + 187500


if __name__ == '__main__': 
	total_income = float(input("What's your \ annual income?\n>>> "))
	tax = calculate_income_tax(total_income) 
	print(f"Total tax applicable at \ ₹{total_income} is ₹{tax}") 


What's your \ annual income?
>>>  1000000


Total tax applicable at \ ₹1000000.0 is ₹75000.0


     22. Write a program that simulates a rock-paper-scissors game against the computer.


In [12]:
#import random module
import random
#main function
def main():
    #intro message
    print("Let's play 'Rock, Paper, Scissors'!")
    #call the user's guess function
    number = user_guess()
    #call the computer's number function
    num = computer_number()
    #call the results function
    results(num, number)

#computer_number function
def computer_number():
    #get a random number in the range of 1 through 3
    num = random.randrange(1,4)
    #if/elif statement
    if num == 1:
        print("Computer chooses rock")
    elif num == 2:
        print("Computer chooses paper")
    elif num == 3:
        print("Computer chooses scissors")
    #return the number
    return num

#user_guess function
def user_guess():
    #get the user's guess
    guess = input("Choose 'rock', 'paper', or 'scissors' by typing that word. ")
    #while guess == 'paper' or guess == 'rock' or guess == 'scissors':
    if is_valid_guess(guess):
        #if/elif statement
        #assign 1 to rock
        if guess == 'rock':
            number = 1
        #assign 2 to paper
        elif guess == 'paper':
            number = 2
        #assign 3 to scissors
        elif guess == 'scissors':
            number = 3
        return number
    else:
        print('That response is invalid.')
        user_guess()

def is_valid_guess(guess):
    if guess == 'rock' or 'paper' or 'scissors':
        status = True
    else:
        status = False
    return status

def restart():
    answer = input("Would you like to play again? Enter 'y' for yes or \
    'n' for no: ")
    #if/elif statement
    if answer == 'y':
        main()
    elif answer == 'n':
        print("Goodbye!")
    else:
        print("Please enter only 'y' or 'n'!")
        #call restart
        restart()

#results function
def results(num, number):
    #find the difference in the two numbers
    difference = num - number
    #if/elif statement
    if difference == 0:
        print("TIE!")
        #call restart
        restart()
    elif difference % 3 == 1:
        print("I'm sorry! You lost :(")
        #call restart
        restart()
    elif difference % 3 == 2:
        print("Congratulations! You won :)")
        #call restart
        restart()

main()

Let's play 'Rock, Paper, Scissors'!


Choose 'rock', 'paper', or 'scissors' by typing that word.  paper


Computer chooses rock
Congratulations! You won :)


Would you like to play again? Enter 'y' for yes or     'n' for no:  n


Goodbye!


     23. Develop a program that generates a random password based on user preferences (length, complexity).


In [ ]:
# importing the random module
import random

# a function that will generate a password on length (n) and return it.
def generatePassword(n):
    # defining the list of choices of characters.
    characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789!@#$%^&*()"

    # initializing an empty string to store the password.
    password = ""

    for i in range(n):
        # randomly selecting one character and appending it to the resultant password string
        password += random.choice(characters)

    # finally returning the randomly generated password.
    return password


if __name__ == "__main__":
    n = int(input("enter a number:"))
    password = generatePassword(n)
    print("A randomly selected password is:", password)

       24. Create a program that implements a simple text-based adventure game with branching scenarios.


In [4]:
answer_yes = ["Yes", "Y", "yes", "y"]
answer_no = ["No", "N", "no", "n"]

print("""
WELCOME! LET'S START THE ADVENTURE

You are standing outside of your house and you see a man running towards you and asking for urgent shelter.

Will you provide shelter to him. (Yes / No)
""")

ans1 = input(">>")

if ans1 in answer_yes:
    print("\nAfter 2 minutes, the Police came to your house, and ask you that whether the thief is in your house or not. Will you say (Yes / No)\n")

    ans2 = input(">>")

    if ans2 in answer_yes:
        print("\nYou are an honest person. He was a thief & You won the Game")

    elif ans2 in answer_no:
        print("\nYou helped a thief. Now, go to Jail. GAME OVER")

  lowerlse:
        print("\nYou typed the wrong input. GOODBYE!")

elif ans1 in answer_no:
    print("\nNow, he is trying to kill you. Will, you knock him down? (Yes / No)\n")

    ans3 = input(">>")

    if ans3 in answer_yes:
        print("\nCongrats! He was a thief & You helped the police to catch him with your bravery.")

    elif ans3 in answer_no:
        print("\nSorry! You are dead. He was a thief & He killed you. GAME OVER")

    else:
        print("\nYou typed the wrong input. GOODBYE!")

else:
    print("\nYou typed the wrong input. GOODBYE!")





WELCOME! LET'S START THE ADVENTURE

You are standing outside of your house and you see a man running towards you and asking for urgent shelter.

Will you provide shelter to him. (Yes / No)



>> y



After 2 minutes, the Police came to your house, and ask you that whether the thief is in your house or not. Will you say (Yes / No)



>> n



You helped a thief. Now, go to Jail. GAME OVER


     25. Build a program that solves a linear equation for x, considering different cases.


In [30]:
# importing library sympy 
from sympy import symbols, Eq, solve 

# defining symbols used in equations 
# or unknown variables 
x, y = symbols('x,y') 

# defining equations 
eq1 = Eq((x+y), 1) 
print("Equation 1:") 
print(eq1) 
eq2 = Eq((x-y), 1) 
print("Equation 2") 
print(eq2) 

# solving the equation 
print("Values of 2 unknown variable are as follows:") 

print(solve((eq1, eq2), (x, y))) 


Equation 1:
Eq(x + y, 1)
Equation 2
Eq(x - y, 1)
Values of 2 unknown variable are as follows:
{x: 1, y: 0}


26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.


     27. Develop a program that determines whether a given year is a prime number or not.


In [2]:
# quiz.py

QUESTIONS = {
    "When was the first known use of the word 'quiz'": [
        "1781", "1771", "1871", "1881"
    ],
    "Which built-in function can get information from the user": [
        "input", "get", "print", "write"
    ],
    "Which keyword do you use to loop over a given list of elements": [
        "for", "while", "each", "loop"
    ],
    "What's the purpose of the built-in zip() function": [
        "To iterate over two or more sequences at the same time",
        "To combine several strings into one",
        "To compress several files into one archive",
        "To get information from the user",
    ],
}

for question, alternatives in QUESTIONS.items():
    correct_answer = alternatives[0]
    for alternative in sorted(alternatives):
        print(f"  - {alternative}")

    answer = input(f"{question}? ")
    if answer == correct_answer:
        print("Correct!")
    else:
        print(f"The answer is {correct_answer!r}, not {answer!r}")

  - 1771
  - 1781
  - 1871
  - 1881


When was the first known use of the word 'quiz'?  1771


The answer is '1781', not '1771'
  - get
  - input
  - print
  - write


Which built-in function can get information from the user?  print


The answer is 'input', not 'print'
  - each
  - for
  - loop
  - while


Which keyword do you use to loop over a given list of elements?  for


Correct!
  - To combine several strings into one
  - To compress several files into one archive
  - To get information from the user
  - To iterate over two or more sequences at the same time


What's the purpose of the built-in zip() function?  to compress several files into one archive


The answer is 'To iterate over two or more sequences at the same time', not 'to compress several files into one archive'


In [1]:
num = int(input("enter the prime number:"))
# If given number is greater than 1
if num > 1:
	# Iterate from 2 to n / 2
	for i in range(2, int(num/2)+1):
		# If num is divisible by any number between
		# 2 and n / 2, it is not prime
		if (num % i) == 0:
			print(num, "is not a prime number")
			break
	else:
		print(num, "is a prime number")
else:
	print(num, "is not a prime number")

enter the prime number: 5


5 is a prime number


     28. Create a program that sorts three numbers in ascending order using conditional statements.


In [38]:
a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = float(input("Enter c: "))

if a > b:
    a,b = b,a
if a > c:
    a,c = c,a
if b > c:
    b,c = c,b
    
print (a, "<", b, "<", c)

Enter a:  15
Enter b:  145
Enter c:  126


15.0 < 126.0 < 145.0


    29. Build a program that determines the roots of a quardtic equation using numerical methods.


In [40]:
# Solve the quadratic equation ax**2 + bx + c = 0

# import complex math module
import cmath

a = int(input())
b = int(input())
c = int(input())

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))


 1
 5
 9


The solution are (-2.5-1.6583123951777j) and (-2.5+1.6583123951777j)


    30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based on the user's input.



In [49]:
#Python program to illustrate 
# how to calculate BMI 
def BMI(height, weight): 
	bmi = weight/(height**2) 
	return bmi 

# Driver code 
height = float(input("enter a height:"))
weight = float(input("enter a weight:"))

# calling the BMI function 
bmi = BMI(height, weight) 
print("The BMI is", format(bmi), "so ", end='') 

# Conditions to find out BMI category 
if (bmi < 18.5): 
	print("underweight") 

elif ( bmi >= 18.5 and bmi < 24.9): 
	print("Healthy") 

elif ( bmi >= 24.9 and bmi < 30): 
	print("overweight") 

elif ( bmi >=30): 
	print("Suffering from Obesity") 

enter a height: 1
enter a weight: 45


The BMI is 45.0 so Suffering from Obesity


                              
                              Challenge Level:
  

     31. Create a program that validates a password based on complexity rules (length, characters, etc.).


In [56]:
import re  
  
def validate_password(password):  
    if len(password) < 8:  
        return False  
    if not re.search("[a-z]", password):  
        return False  
    if not re.search("[A-Z]", password):  
        return False  
    if not re.search("[0-9]", password):  
        return False  
    return True  
  
password = "P@ssw0rd"  
if validate_password(password):  
    print("Valid password")  
else:  
    print("Invalid password")  

Valid password


     32. Develop a program that performs matrix addition and subtraction based on user input.


In [36]:
# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))


Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


    33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean algorithm.



In [65]:
# Python3 program to demonstrate Basic Euclidean Algorithm


# Function to return gcd of a and b
def gcd(a, b):
	if a == 0:
		return b

	return gcd(b % a, a)
# Driver code
a = 10
b = 15
print("gcd(", a, ",", b, ") = ", gcd(a, b))

a = 35
b = 10
print("gcd(", a, ",", b, ") = ", gcd(a, b))

a = 31
b = 2
print("gcd(", a, ",", b, ") = ", gcd(a, b))

# Code Contributed By Mohit Gupta_OMG <(0_o)>


gcd( 10 , 15 ) =  5
gcd( 35 , 10 ) =  5
gcd( 31 , 2 ) =  1


     34. Build a program that performs matrix multiplication using nested loops and conditional statements.


In [69]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


     35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.


In [56]:
# Tic-Tac-Toe Program using
# random number in Python
 
# importing all necessary libraries
import numpy as np
import random
from time import sleep
 
# Creates an empty board
 
 
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
 
# Check for empty places on board
 
 
def possibilities(board):
    l = []
 
    for i in range(len(board)):
        for j in range(len(board)):
 
            if board[i][j] == 0:
                l.append((i, j))
    return(l)
 
# Select a random place for the player
 
 
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)
 
# Checks whether the player has three
# of their marks in a horizontal row
 
 
def row_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a vertical row
 
 
def col_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a diagonal row
 
 
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
 
# Evaluates whether there is
# a winner or a tie
 
 
def evaluate(board):
    winner = 0
 
    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
 
            winner = player
 
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner
 
# Main function to start the game
 
 
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
 
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return(winner)
 
 
# Driver Code
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 1]
 [0 0 0]]
Board after 2 move
[[0 0 0]
 [0 0 1]
 [2 0 0]]
Board after 3 move
[[0 0 0]
 [1 0 1]
 [2 0 0]]
Board after 4 move
[[0 0 0]
 [1 2 1]
 [2 0 0]]
Board after 5 move
[[0 0 0]
 [1 2 1]
 [2 0 1]]
Board after 6 move
[[0 0 2]
 [1 2 1]
 [2 0 1]]
Winner is: 2


     36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.


In [62]:
def PrintFibonacci(length):
    #Initial variable for the base case. 
    first = 0
    second = 1

    #Printing the initial Fibonacci number.
    print(first, second, end=" ")

    #decreasing the length by two because the first 2 Fibonacci numbers 
    #already printed.
    length -= 2
    
    #Loop until the length becomes 0.
    while length > 0:

        #Printing the next Fibonacci number.
        print(first + second, end=" ")

        #Updating the first and second variables for finding the next number. 
        temp = second
        second = first + second
        first = temp

        #Decreasing the length that states the Fibonacci numbers to be 
        #printed more.
        length -= 1

if __name__ == "__main__":
    print("Fibonacci Series - ")
    PrintFibonacci(7)
    pass

Fibonacci Series - 
0 1 1 2 3 5 8 

37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.


In [59]:
# Function for nth Fibonacci number

def Fibonacci(n):
	if n<= 0:
		print("Incorrect input")
	# First Fibonacci number is 0
	elif n == 1:
		return 0
	# Second Fibonacci number is 1
	elif n == 2:
		return 1
	else:
		return Fibonacci(n-1)+Fibonacci(n-2)

# Driver Program

print(Fibonacci(20))


4181


38. Create a program that generates a calendar for a given month and year using conditional statements.


In [55]:
# Python program to display calendar of 
# given month of the year 

# import module 
import calendar 

yy = int(input("enter the year:"))
mm = int(input("enter the month:"))

# display the calendar 
print(calendar.month(yy, mm)) 


enter the year: 2024
enter the month: 4


     April 2024
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30



    39. Build a program that simulates a basic text-based blackjack game against the computer.


In [ ]:
def card_value(card):
    """Returns the integer value of a single card."""

    rank = card[0]
    if rank in ranks[0:-4]:
        return int(rank)
    elif rank is 'ACE':
        return 11
    else:
        return 10

def hand_value(hand):
    """Returns the integer value of a set of cards."""

    # Naively sum up the cards in the deck.
    tmp_value = sum(card_value(_) for _ in hand)
    # Count the number of Aces in the hand.
    num_aces = len([_ for _ in hand if _[0] is 'ACE'])

    # Aces can count for 1, or 11. If it is possible to bring the value of 
    #the hand under 21 by making 11 -> 1 substitutions, do so.
    while num_aces > 0:

        if tmp_value > 21 and 'ACE' in ranks:
            tmp_value -= 10
            num_aces -= 1
        else:
            break

    # Return a string and an integer representing the value of the hand. If 
    # the hand is bust, return 100.
    if tmp_value < 21:
        return [str(tmp_value), tmp_value]
    elif tmp_value == 21:
        return ['Blackjack!', 21]
    else:
        return ['Bust!', 100]

     40. Write a program that generates the prime factors of a given number using trial division.



In [ ]:
# Python program to print prime factors

import math

# A function to print all prime factors of
# a given number n
def primeFactors(n):
	
	# Print the number of two's that divide n
	while n % 2 == 0:
		print(2)
		n = n // 2
		
	# n must be odd at this point
	# so a skip of 2 ( i = i + 2) can be used
	for i in range(3,int(math.sqrt(n))+1,2):
		
		# while i divides n , print i ad divide n
		while n % i== 0:
			print(i)
			n = n // i
			
	# Condition if n is a prime
	# number greater than 2
	if n > 2:
		print(n)
		
# Driver Program to test above function

n = 315
primeFactors(n)

# This code is contributed by Harshit Agrawal 
#Code Improved by Sarthak Shrivastava
